### ISSUE TITLE
search by compte proprietaire/lot fails

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-cadastrapp#154]
using https://github.com/georchestra/mapstore2-cadastrapp/commit/e9c934257b88b7c075b0e416b230fe9d14815a18 (and i've looked in history for potential fixes) on firefox, when connected and trying to look for a compte proprietaire by id

![image](https://user-images.githubusercontent.com/3421760/166465999-8767098b-27fc-4a0f-8ae4-2c62ed638ed9.png)

it fails with a js error:
```
15:45:05.435 Error in epic "cadastrappSearch". Original error: TypeError: y is undefined
    Xf https://ids.craig.fr/mapstore/rest/config/loadasset/dist/extensions/Cadastrapp/assets/js/831.30fdd81b.js:1
    Xf https://ids.craig.fr/mapstore/rest/config/loadasset/dist/extensions/Cadastrapp/assets/js/831.30fdd81b.js:1
    _next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    _next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    u https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    u https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
geOrchestra.js:2:4361105
15:45:05.558 Uncaught TypeError: y is undefined
    Xf https://ids.craig.fr/mapstore/rest/config/loadasset/dist/extensions/Cadastrapp/assets/js/831.30fdd81b.js:1
    Xf https://ids.craig.fr/mapstore/rest/config/loadasset/dist/extensions/Cadastrapp/assets/js/831.30fdd81b.js:1
    _next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    _next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    u https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    u https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
831.30fdd81b.js:1:462335
```

same thing with chrome

when searching by lot with a file containing a single line, it also fails:
```
15:52:56.036 Error in epic "cadastrappOwnersSearch". Original error: TypeError: n is undefined
    Jf https://ids.craig.fr/mapstore/rest/config/loadasset/dist/extensions/Cadastrapp/assets/js/831.30fdd81b.js:1
    _next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    _next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    u https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    u https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    default https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    v https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    onSearch https://ids.craig.fr/mapstore/rest/config/loadasset/dist/extensions/Cadastrapp/assets/js/831.30fdd81b.js:1
    m https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    _ https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    S https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    S https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    P https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    T https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    A https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    yn https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    ue https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    xn https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    En https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    On https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    unstable_runWithPriority https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    Bo https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    Ks https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    wn https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
geOrchestra.js:2:4361105
15:52:56.217 Uncaught TypeError: n is undefined
    Jf https://ids.craig.fr/mapstore/rest/config/loadasset/dist/extensions/Cadastrapp/assets/js/831.30fdd81b.js:1
    _next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    _next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    next https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    u https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    u https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    default https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    v https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    onSearch https://ids.craig.fr/mapstore/rest/config/loadasset/dist/extensions/Cadastrapp/assets/js/831.30fdd81b.js:1
    m https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    _ https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    S https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    S https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    P https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    T https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    A https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    yn https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    ue https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    xn https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    En https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    On https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    unstable_runWithPriority https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    Bo https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    Ks https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
    wn https://ids.craig.fr/mapstore/dist/geOrchestra.js?27fcd78559b59d8442b8:2
831.30fdd81b.js:1:465510
```

@catmorales @MaelREBOUX do you see the same ? i know @jusabatier does experience it too.

**Comment by jusabatier** [comment]
Here I use chromium and I get when searching by owner account : 

```
Error in epic "cadastrappSearch". Original error: TypeError: Cannot read properties of undefined (reading 'value')
    at searchType (501.4d777c35.js:1:469163)
    at t.project (501.4d777c35.js:1:470744)
    at t._next (geOrchestra.js?88b201feb0e0c40cf124:2:8990670)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8860713)
    at t._next (geOrchestra.js?88b201feb0e0c40cf124:2:8948524)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8860713)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8857591)
    at geOrchestra.js?88b201feb0e0c40cf124:2:8822590
    at geOrchestra.js?88b201feb0e0c40cf124:2:8822576
    at geOrchestra.js?88b201feb0e0c40cf124:2:8823411
    at t.dispatch [as _next] (geOrchestra.js?88b201feb0e0c40cf124:2:8830671)
    at t.__tryOrUnsub (geOrchestra.js?88b201feb0e0c40cf124:2:8862635)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8861961)
    at t._next (geOrchestra.js?88b201feb0e0c40cf124:2:8861042)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8860713)
    at t.notifyNext (geOrchestra.js?88b201feb0e0c40cf124:2:8991321)
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
t.error @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
dispatch @ geOrchestra.js?88b201feb0e0c40cf124:2
t.__tryOrUnsub @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.notifyNext @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.notifyNext @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.notifyNext @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.notifyNext @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.notifyNext @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.notifyNext @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.notifyNext @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.notifyNext @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.subscribeToResult @ geOrchestra.js?88b201feb0e0c40cf124:2
t._innerSub @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.notifyNext @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
Promise.then (asynchrone)
t.subscribeToResult @ geOrchestra.js?88b201feb0e0c40cf124:2
t._callFactory @ geOrchestra.js?88b201feb0e0c40cf124:2
t.tryDefer @ geOrchestra.js?88b201feb0e0c40cf124:2
t @ geOrchestra.js?88b201feb0e0c40cf124:2
t._subscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e._trySubscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e.subscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e.call @ geOrchestra.js?88b201feb0e0c40cf124:2
e.subscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
t.subscribeToResult @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t._subscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e._trySubscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e.subscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e.call @ geOrchestra.js?88b201feb0e0c40cf124:2
e.subscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
t.subscribeToResult @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t._subscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e._trySubscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e.subscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e.call @ geOrchestra.js?88b201feb0e0c40cf124:2
e.subscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e._subscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e._trySubscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
e.subscribe @ geOrchestra.js?88b201feb0e0c40cf124:2
t.subscribeToResult @ geOrchestra.js?88b201feb0e0c40cf124:2
t._innerSub @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
onSearch @ 501.4d777c35.js:1
m @ geOrchestra.js?88b201feb0e0c40cf124:2
_ @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
C @ geOrchestra.js?88b201feb0e0c40cf124:2
M @ geOrchestra.js?88b201feb0e0c40cf124:2
O @ geOrchestra.js?88b201feb0e0c40cf124:2
A @ geOrchestra.js?88b201feb0e0c40cf124:2
gn @ geOrchestra.js?88b201feb0e0c40cf124:2
ce @ geOrchestra.js?88b201feb0e0c40cf124:2
En @ geOrchestra.js?88b201feb0e0c40cf124:2
Sn @ geOrchestra.js?88b201feb0e0c40cf124:2
xn @ geOrchestra.js?88b201feb0e0c40cf124:2
t.unstable_runWithPriority @ geOrchestra.js?88b201feb0e0c40cf124:2
zo @ geOrchestra.js?88b201feb0e0c40cf124:2
Ks @ geOrchestra.js?88b201feb0e0c40cf124:2
wn @ geOrchestra.js?88b201feb0e0c40cf124:2
Afficher 75 autres frames
geOrchestra.js?88b201feb0e0c40cf124:2 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at searchType (501.4d777c35.js:1:469163)
    at t.project (501.4d777c35.js:1:470744)
    at t._next (geOrchestra.js?88b201feb0e0c40cf124:2:8990670)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8860713)
    at t._next (geOrchestra.js?88b201feb0e0c40cf124:2:8948524)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8860713)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8857591)
    at geOrchestra.js?88b201feb0e0c40cf124:2:8822590
    at geOrchestra.js?88b201feb0e0c40cf124:2:8822576
    at geOrchestra.js?88b201feb0e0c40cf124:2:8823411
    at t.dispatch [as _next] (geOrchestra.js?88b201feb0e0c40cf124:2:8830671)
    at t.__tryOrUnsub (geOrchestra.js?88b201feb0e0c40cf124:2:8862635)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8861961)
    at t._next (geOrchestra.js?88b201feb0e0c40cf124:2:8861042)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8860713)
    at t.notifyNext (geOrchestra.js?88b201feb0e0c40cf124:2:8991321)
```

And I get when searching owners by lot :

```
Error in epic "cadastrappOwnersSearch". Original error: TypeError: Cannot read properties of undefined (reading 'cgocommune')
    at t.project (501.4d777c35.js:1:472338)
    at t._next (geOrchestra.js?88b201feb0e0c40cf124:2:8990670)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8860713)
    at t._next (geOrchestra.js?88b201feb0e0c40cf124:2:8948524)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8860713)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8857591)
    at geOrchestra.js?88b201feb0e0c40cf124:2:8822590
    at geOrchestra.js?88b201feb0e0c40cf124:2:8822576
    at geOrchestra.js?88b201feb0e0c40cf124:2:8823411
    at geOrchestra.js?88b201feb0e0c40cf124:2:8829849
    at onSearch (501.4d777c35.js:1:255276)
    at Object.m (geOrchestra.js?88b201feb0e0c40cf124:2:7706894)
    at _ (geOrchestra.js?88b201feb0e0c40cf124:2:7707037)
    at geOrchestra.js?88b201feb0e0c40cf124:2:7707183
    at C (geOrchestra.js?88b201feb0e0c40cf124:2:7707269)
    at M (geOrchestra.js?88b201feb0e0c40cf124:2:7707718)
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
t.error @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t._next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
t.next @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
onSearch @ 501.4d777c35.js:1
m @ geOrchestra.js?88b201feb0e0c40cf124:2
_ @ geOrchestra.js?88b201feb0e0c40cf124:2
(anonyme) @ geOrchestra.js?88b201feb0e0c40cf124:2
C @ geOrchestra.js?88b201feb0e0c40cf124:2
M @ geOrchestra.js?88b201feb0e0c40cf124:2
O @ geOrchestra.js?88b201feb0e0c40cf124:2
A @ geOrchestra.js?88b201feb0e0c40cf124:2
gn @ geOrchestra.js?88b201feb0e0c40cf124:2
ce @ geOrchestra.js?88b201feb0e0c40cf124:2
En @ geOrchestra.js?88b201feb0e0c40cf124:2
Sn @ geOrchestra.js?88b201feb0e0c40cf124:2
xn @ geOrchestra.js?88b201feb0e0c40cf124:2
t.unstable_runWithPriority @ geOrchestra.js?88b201feb0e0c40cf124:2
zo @ geOrchestra.js?88b201feb0e0c40cf124:2
Ks @ geOrchestra.js?88b201feb0e0c40cf124:2
wn @ geOrchestra.js?88b201feb0e0c40cf124:2
geOrchestra.js?88b201feb0e0c40cf124:2 Uncaught TypeError: Cannot read properties of undefined (reading 'cgocommune')
    at t.project (501.4d777c35.js:1:472338)
    at t._next (geOrchestra.js?88b201feb0e0c40cf124:2:8990670)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8860713)
    at t._next (geOrchestra.js?88b201feb0e0c40cf124:2:8948524)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8860713)
    at t.next (geOrchestra.js?88b201feb0e0c40cf124:2:8857591)
    at geOrchestra.js?88b201feb0e0c40cf124:2:8822590
    at geOrchestra.js?88b201feb0e0c40cf124:2:8822576
    at geOrchestra.js?88b201feb0e0c40cf124:2:8823411
    at geOrchestra.js?88b201feb0e0c40cf124:2:8829849
    at onSearch (501.4d777c35.js:1:255276)
    at Object.m (geOrchestra.js?88b201feb0e0c40cf124:2:7706894)
    at _ (geOrchestra.js?88b201feb0e0c40cf124:2:7707037)
    at geOrchestra.js?88b201feb0e0c40cf124:2:7707183
    at C (geOrchestra.js?88b201feb0e0c40cf124:2:7707269)
    at M (geOrchestra.js?88b201feb0e0c40cf124:2:7707718) 
```

**Comment by MaelREBOUX** [comment]
Same error here.

Cadastrapp ms2 v 1.0.0-rc 20 + cadastrapp API v 1.9

**Comment by landryb** [comment]
issue is still present with ms2-cadastrapp `v2.0.0-rc`, and that's not related to the backend version since zero query is done. Pure client-side issue. @tdipisa @catmorales ?

**Comment by landryb** [comment]
after fighting for a while with running ms2 in debug mode and hacking many things around to have authentication working via headers, i've managed to get a more meaningful trace of the error when searching by "compte proprietaire":
```
Uncaught TypeError: proprietaire is undefined
    searchParcelles search.js:112
    cadastrappSearch search.js:175
```
more on this next week.

**Comment by landryb** [comment]
after looking, the wrong case is taken here https://github.com/georchestra/mapstore2-cadastrapp/blob/master/js/extension/epics/search.js#L109 - `searchType` is `user` (and thus expects `proprietaire`) while `rawParams` has `commune` and `dnupro`.

**Comment by landryb** [comment]
regression from #127

**Comment by catmorales** [comment]
Search by compte propriétaire tested today.

1- on portail.sig.rennesmetropole.fr (production)
Version: 
* MapStore2-geOrchestra	:[2021.02.xx](https://github.com/georchestra/mapstore2-georchestra/commits/2021.02.xx)[(6b4d11e8)](https://github.com/georchestra/mapstore2-georchestra/commit/6b4d11e83e0d7a411e785845b72e91507aed460d)
* MapStore2	:[2021.02.xx](https://github.com/geosolutions-it/MapStore2/commits/2021.02.xx)[(e7e210c2)](https://github.com/geosolutions-it/MapStore2/commit/e7e210c2f551714a92ab0ed0e17a3398b1d996c3)
*  Cadastrapp-v1.9
* Mapstore2-cadastrapp build  [6dc47919](https://github.com/georchestra/mapstore2-cadastrapp/commit/6dc479190f2d7d75e3da06a90eeefcd241415368)

It doesn't work , we have no result.
And i have tested with a valid "compte-propriétaire" which is mine

2- on portail-test (test)
Version 
Mapstore2 2022.01.xx
Mapstore2-georchestra 2022.01.xx
Back end Cadastrapp-v1.9-37
Front End  v2.0.0-rc - build https://github.com/georchestra/mapstore2-cadastrapp/commit/3cab1bab1a82e89f7a02eb73fcb24bea0c345b80

It doesn't work , we have no result.
And i have tested with a valid "compte-propriétaire" which is mine

On the VA tests (May10 of .2021) ,it was working and had been tested. I've just mentionned that:
```
propriétaire
- par nom usage OK
- par nom de naissance ok
- par compte propriétaire (récupéré depuis l'export
propriétaire -attention à retirer le numéro de la
commune- 350001P00437 fonctionne avec P00437)
- par lot OK
```
@tdipisa , So I  Confirm it's a regression and not linked to the Back end version.

**Comment by landryb** [comment]
#171 fixes it for me but i dunno if the usecases mentioned/fixed by #127 still work - need testing.

**Comment by catmorales** [comment]
I've tested , just now  the search by account with the fix of @landryb and it works 👍
